### ISSUE TITLE
Thought: document.elementFromPoint?

### ISSUE THREAD

**Issue by developit** [syropian/find-my-el#1]
This seems similar to [document.elementFromPoint()](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint). Thoughts?

**Comment by syropian** [comment]
Similar, but with a few key differences. One being you can restrict what nodes get included in the check, and the other being that it finds the element closest to the given coordinates. This means the element doesn't have to be at [x, y], it just has to be the closest element in the node list to it. 

Hope that clears some things up!

**Comment by developit** [comment]
Makes sense. I wonder if there is a way to use elementFromPoint to speed up the detection?

**Comment by syropian** [comment]
The problem with elementFromPoint is it never guarantees a certain subset of elements, and it always looks at the top level window. `find-my-el` lets you pass your own elements to check, and also allows you to check within the bounds of a certain container, if you don't want it to look at the window as a whole. AFAIK using `elementFromPoint` would require a lot of back-and-forth parent-child checking which is likely slower than the current implementation. The demo folder uses a container, and checks for the center-most element on scroll, and it seems quite fast and responsive, considering how many events a scroll can fire off. :)

**Comment by developit** [comment]
Ah that makes sense. It'd never work for a subset of the document's elements. Gotcha!
